site_name: PowerRestCLI
repo_url: https://github.com/jpsider/PowerRestCLI
theme: readthedocs
pages:
- Home: index.md
- PowerRestCLI Basics:
  - What is PowerRestCLI: about.md
  - Quick Start: Quick-Start-Installation-and-Example.md
- Basic Commands:
- Examples:
- Acknowledgements: acknowledgements.md
